version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11

  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet restore
    - echo Build ends on 'date'

  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet build
    - dotnet test --logger:junit
    - echo Build ends on 'date'

  post_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet publish
    - mv target/*.dll ROOT.dll
    - echo Build edns on 'date'

artifacts:
  files:
    - ROOT.dll
  name: hello-word-artifact

